Remove decode() as its not needed for versions 3.8 +
CuriousLearner/django-phone-verify pull request #53
Opened 2021-02-01 13:27 UTC by m7salam

this should prevent the error of the str in decode we get if using version 3.8.5 or above

2021-02-01 13:28 UTC, m7salam commented
its related to this issue https://github.com/CuriousLearner/django-phone-verify/issues/51

2021-02-04 15:52 UTC, CuriousLearner commented
Hi @m7salam 👋 

Thank you for the PR.

The CI is failing https://travis-ci.com/github/CuriousLearner/django-phone-verify/builds/215598946#L351

Let me know once you fix it and I'll take a look at this and test the fix for various python versions.

Many thanks!

2021-02-04 15:53 UTC, CuriousLearner commented on .vscode/settings.json
> +}
While, you're at it, please remove this config file.

2021-02-09 13:12 UTC, m7salam commented
@CuriousLearner its already ready and passed the checks :)

2021-02-10 05:59 UTC, CuriousLearner requested changes

2021-02-10 05:59 UTC, CuriousLearner commented on phone_verify/backends/base.py
> +        #     return jwt.encode(data, django_settings.SECRET_KEY)
This fix is commented out.

2021-03-29 18:23 UTC, CuriousLearner commented
This had the fix commented out and is now superseded by #58 

Thanks for your efforts @m7salam !

2021-03-29 18:23 UTC, closed without merging

2021-03-29 18:33 UTC, m7salam commented
@CuriousLearner the comment wasn't the solution it was the old one and I commented it when I solved it by following by updating a certain library you were using I found the updated version solved the problem so I made the update and pushed it and it succeeded all the tests 

So the comments are useless it just needs to be removed and I'm sorry I didn't have time between work and got sick to remove it and push it 

It's already passing all your tests and working well

2021-03-29 19:02 UTC, CuriousLearner commented
Ok, no problem. I think everything will work from #58. I'm just waiting for CI to pass for each of the commits. Currently it seems like travis is having some issues and cancelling the builds mid-way.

So, I'm gonna fix those and release a new version.

Anyways, thanks for your time. I really appreciate it. :)